spring:
    application:
        name: creditManagerARM
    datasource:
        url: jdbc:postgresql://localhost:5432/creditmanager_db
        username: postgres
        password: 2305
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format-sql: true
            
